/* automatically generated by rust-bindgen 0.70.1 */

use crate::deps::*;
use crate::acb_types::*;
use crate::arb_types::*;
use crate::flint::*;
use crate::fmpz_types::*;


pub const ARB_FMPZ_POLY_ROOTS_VERBOSE: u32 = 1;
extern "C" {
    pub fn _arb_fmpz_poly_evaluate_acb_horner(
        res: *mut acb_struct,
        f: *const fmpz,
        len: mp_limb_signed_t,
        x: *const acb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_evaluate_acb_horner(
        res: *mut acb_struct,
        f: *const fmpz_poly_struct,
        a: *const acb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn _arb_fmpz_poly_evaluate_acb_rectangular(
        res: *mut acb_struct,
        f: *const fmpz,
        len: mp_limb_signed_t,
        x: *const acb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_evaluate_acb_rectangular(
        res: *mut acb_struct,
        f: *const fmpz_poly_struct,
        a: *const acb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn _arb_fmpz_poly_evaluate_acb(
        res: *mut acb_struct,
        f: *const fmpz,
        len: mp_limb_signed_t,
        x: *const acb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_evaluate_acb(
        res: *mut acb_struct,
        f: *const fmpz_poly_struct,
        a: *const acb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn _arb_fmpz_poly_evaluate_arb_horner(
        res: *mut arb_struct,
        f: *const fmpz,
        len: mp_limb_signed_t,
        x: *const arb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_evaluate_arb_horner(
        res: *mut arb_struct,
        f: *const fmpz_poly_struct,
        a: *const arb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn _arb_fmpz_poly_evaluate_arb_rectangular(
        res: *mut arb_struct,
        f: *const fmpz,
        len: mp_limb_signed_t,
        x: *const arb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_evaluate_arb_rectangular(
        res: *mut arb_struct,
        f: *const fmpz_poly_struct,
        a: *const arb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn _arb_fmpz_poly_evaluate_arb(
        res: *mut arb_struct,
        f: *const fmpz,
        len: mp_limb_signed_t,
        x: *const arb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_evaluate_arb(
        res: *mut arb_struct,
        f: *const fmpz_poly_struct,
        a: *const arb_struct,
        prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_deflate(
        result: *mut fmpz_poly_struct,
        input: *const fmpz_poly_struct,
        deflation: mp_limb_t,
    );
    pub fn arb_fmpz_poly_deflation(input: *const fmpz_poly_struct) -> mp_limb_t;
    pub fn arb_fmpz_poly_complex_roots(
        roots: acb_ptr,
        poly: *const fmpz_poly_struct,
        flags: libc::c_int,
        target_prec: mp_limb_signed_t,
    );
    pub fn arb_fmpz_poly_gauss_period_minpoly(
        res: *mut fmpz_poly_struct,
        q: mp_limb_t,
        n: mp_limb_t,
    );
}
