/* automatically generated by rust-bindgen 0.70.1 */

use crate::deps::*;
use crate::fq_types::*;


extern "C" {
    pub fn FQ_POLY_ITERATED_FROBENIUS_CUTOFF(
        ctx: *const fq_ctx_struct,
        length: mp_limb_signed_t,
    ) -> libc::c_int;
    pub fn fq_poly_factor_get_poly(
        z: *mut fq_poly_struct,
        fac: *const fq_poly_factor_struct,
        i: mp_limb_signed_t,
        ctx: *const fq_ctx_struct,
    );
}
