/* automatically generated by rust-bindgen 0.70.1 */

#![allow(non_camel_case_types)]
use crate::deps::*;
use crate::flint::*;
use libc::{c_char, c_int, c_uint, c_void, size_t, FILE};


extern "C" {
    pub fn _perm_randtest(
        vec: *mut mp_limb_signed_t,
        n: mp_limb_signed_t,
        state: *mut flint_rand_s,
    ) -> ::std::os::raw::c_int;
    pub fn _perm_parity(vec: *const mp_limb_signed_t, n: mp_limb_signed_t)
        -> ::std::os::raw::c_int;
}
